apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: godaddytest
  name: godaddytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godaddytest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: godaddytest
    spec:
      containers:
      - image: godaddytest
        name: godaddytest
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 7000
status: {}